name: NestJS CI/CD

on:
  push:
    branches: [master]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Kodni klonlash
        uses: actions/checkout@v3

      - name: Node.js o'rnatish
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: PNPM o'rnatish
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Dependenciyalarni o'rnatish
        run: pnpm install --frozen-lockfile

      - name: Lint tekshirish
        run: pnpm run lint

      - name: Testlarni ishga tushirish
        run: pnpm run test

      - name: Build qilish
        run: pnpm run build
